### ISSUE TITLE
[ERROR] up on using the roulette table

### ISSUE THREAD

**Issue by Greazi-Times** [aematsubara/Roulette#2]
When I am using the roulette table I get this error spammed inside my console

```
Could not render map using renderer me.matsubara.roulette.util.map.MapBuilder$1
java.lang.IllegalArgumentException: Text contains unterminated color string
        at org.bukkit.craftbukkit.v1_17_R1.map.CraftMapCanvas.drawText(CraftMapCanvas.java:104) ~[patched_1.17.1.jar:git-Purpur-1428]
        at me.matsubara.roulette.util.map.MapBuilder$1.lambda$render$0(MapBuilder.java:188) ~[Roulette-1.7-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.matsubara.roulette.util.map.MapBuilder$1.render(MapBuilder.java:188) ~[Roulette-1.7-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.map.CraftMapView.render(CraftMapView.java:159) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData$HoldingPlayer.nextUpdatePacket(MapItemSavedData.java:630) ~[app:?]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.getUpdatePacket(MapItemSavedData.java:434) ~[app:?]
        at net.minecraft.world.item.MapItem.getUpdatePacket(MapItem.java:370) ~[app:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:697) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:331) ~[app:?]
        at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1681) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by aematsubara** [comment]
Hi, for now colors aren't supported in maps by this plugin, remove colors from @map-image.text and should be fine. I'll add a fix for this in the next update so no exception is thrown

**Comment by Greazi-Times** [comment]
oke thank you for the reply
