### ISSUE TITLE
Version 1.9.3 dropped 1.19.2 support?

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#25]
```
[16:24:28] [Server thread/INFO]: [PlugMan] Roulette wurde entladen.
[16:24:31] [Server thread/INFO]: [Roulette] Enabling Roulette v1.9.3
[16:24:31] [Server thread/INFO]: [Roulette] Using CMIEInjector as the economy provider.
[16:24:31] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: roulette [1.9.3]
[16:24:31] [Server thread/INFO]: [Roulette] All chips have been loaded from chips.yml!

--- This is spammed a view hundered times. So i just pasted it once  ---
[16:24:31] [Server thread/WARN]: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(int,DataWatcher,boolean)PacketPlayOutEntityMetadata to (int,Object)Object
[16:24:31] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
[16:24:31] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
[16:24:31] [Server thread/WARN]: 	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.createMetadataPacket(PacketStand.java:781)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.updateMetadata(PacketStand.java:772)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.setOnFire(PacketStand.java:505)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:281)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:255)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.addNew(Model.java:188)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.loadModel(Model.java:250)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.<init>(Model.java:104)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:127)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:397)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:117)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:500)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:24:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:24:31] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "packet" is null
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.sendPacket(PacketStand.java:842)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.sendPacket(PacketStand.java:838)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.updateMetadata(PacketStand.java:772)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.setOnFire(PacketStand.java:505)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:281)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:255)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.addNew(Model.java:188)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.loadModel(Model.java:250)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.model.Model.<init>(Model.java:104)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[16:24:31] [Server thread/WARN]: 	at Roulette_1.9.3.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:127)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:397)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:117)
[16:24:31] [Server thread/WARN]: 	at PlugManX_2.3.1.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[16:24:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:500)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[16:24:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:24:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
--- This is spammed a view hundered times. So i just pasted it once  ---

[16:24:31] [Server thread/ERROR]: [31m[Minecraft] Error occurred while enabling Roulette v1.9.3 (Is it up to date?)[0m
java.lang.NoSuchFieldError: FEATURE_PREVIEW_UPDATE
	at me.matsubara.roulette.npc.NPC.<clinit>(NPC.java:44) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.game.Game.setNPC(Game.java:227) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.game.Game.<init>(Game.java:140) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.manager.GameManager.add(GameManager.java:81) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.manager.GameManager.update(GameManager.java:201) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.manager.GameManager.load(GameManager.java:46) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35) ~[Roulette_1.9.3.jar:?]
	at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:127) ~[Roulette_1.9.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:397) ~[PlugManX_2.3.1.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:117) ~[PlugManX_2.3.1.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX_2.3.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by aematsubara** [comment]
Should be fixed in the latest update, make another issue if this happen again; thanks for reporting!
