### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Floodo** [aematsubara/Roulette#26]
Hi, when I want to start server, this warn shows up (that repeats like 20 times), but the plugin after like 5 seconds disables itself.
Paper 1.19 (Waterfall + Geyser)
Roulette 1.9.3

[10:25:06 WARN]: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(int,DataWatcher,boolean)PacketPlayOutEntityMetadata to (int,Object)Object
[10:25:06 WARN]:        at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:884)
[10:25:06 WARN]:        at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:869)
[10:25:06 WARN]:        at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.createMetadataPacket(PacketStand.java:781)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.updateMetadata(PacketStand.java:772)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.setOnFire(PacketStand.java:505)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:281)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:255)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.addNew(Model.java:188)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.loadModel(Model.java:250)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.<init>(Model.java:104)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:127)
[10:25:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:25:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:25:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[10:25:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
[10:25:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420)
[10:25:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1122)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[10:25:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:25:06 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "packet" is null
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.sendPacket(PacketStand.java:842)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.sendPacket(PacketStand.java:838)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.updateMetadata(PacketStand.java:772)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.setOnFire(PacketStand.java:505)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:281)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.stand.PacketStand.<init>(PacketStand.java:255)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.addNew(Model.java:188)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.loadModel(Model.java:250)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.model.Model.<init>(Model.java:104)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[10:25:06 WARN]:        at Roulette-1.9.3.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:127)
[10:25:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:25:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:25:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[10:25:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
[10:25:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420)
[10:25:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1122)
[10:25:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[10:25:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by aematsubara** [comment]
Should be fixed in the latest update, make another issue if this happen again; thanks for reporting!
