### ISSUE TITLE
Issue with Paper 1.19.2 and Version 1.9.3.2 - citicens dailer cant be loaded..

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#27]
when i went to the chunks where our roulette tables are i get this error once.
The tables also seems to be not there anymore.. :(

```
[13:42:40 WARN]: [Roulette] Plugin Roulette v1.9.3.1 generated an exception while executing task 50038689
java.lang.NoSuchFieldError: UPDATE_LISTED
    at me.matsubara.roulette.npc.modifier.VisibilityModifier.<clinit>(VisibilityModifier.java:25) ~[Roulette_1.9.3.1.jar:?]
    at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
    at me.matsubara.roulette.npc.NPC.show(NPC.java:122) ~[Roulette_1.9.3.1.jar:?]
    at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.1.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
>....
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[13:42:41 WARN]: [Roulette] Plugin Roulette v1.9.3.1 generated an exception while executing task 50038689
java.lang.NoClassDefFoundError: Could not initialize class me.matsubara.roulette.npc.modifier.VisibilityModifier
    at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
    at me.matsubara.roulette.npc.NPC.show(NPC.java:122) ~[Roulette_1.9.3.1.jar:?]
    at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.1.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Wen i reloaded with version 1.9.2.1 the tables are back :)
so it means te data itself is not lost :)

**Comment by CloudeLecaw** [comment]
and a secound one.. i dont know if the secound one is a related one because the plugin was disabling on unloading. so may just for information...

```
[13:45:12 INFO]: [Roulette] Disabling Roulette v1.9.3.1
>....
[13:45:12 ERROR]: [Minecraft] Error occurred while disabling Roulette v1.9.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.matsubara.roulette.npc.modifier.VisibilityModifier
	at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
	at me.matsubara.roulette.game.Game.remove(Game.java:902) ~[Roulette_1.9.3.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at me.matsubara.roulette.RoulettePlugin.onDisable(RoulettePlugin.java:182) ~[Roulette_1.9.3.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
>....at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:575) ~[PlugManX_2.3.1.jar:?]
	at com.rylinaux.plugman.command.UnloadCommand.execute(UnloadCommand.java:112) ~[PlugManX_2.3.1.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX_2.3.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-307]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
```

**Comment by aematsubara** [comment]
> when i went to the chunks where our roulette tables are i get this error once. The tables also seems to be not there anymore.. :(
> 
> ```
> [13:42:40 WARN]: [Roulette] Plugin Roulette v1.9.3.1 generated an exception while executing task 50038689
> java.lang.NoSuchFieldError: UPDATE_LISTED
>     at me.matsubara.roulette.npc.modifier.VisibilityModifier.<clinit>(VisibilityModifier.java:25) ~[Roulette_1.9.3.1.jar:?]
>     at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
>     at me.matsubara.roulette.npc.NPC.show(NPC.java:122) ~[Roulette_1.9.3.1.jar:?]
>     at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.1.jar:?]
>     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
>     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
>     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>     at java.lang.Thread.run(Thread.java:833) ~[?:?]
> >....
> at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
> [13:42:41 WARN]: [Roulette] Plugin Roulette v1.9.3.1 generated an exception while executing task 50038689
> java.lang.NoClassDefFoundError: Could not initialize class me.matsubara.roulette.npc.modifier.VisibilityModifier
>     at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
>     at me.matsubara.roulette.npc.NPC.show(NPC.java:122) ~[Roulette_1.9.3.1.jar:?]
>     at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.1.jar:?]
>     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
>     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>     at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> Wen i reloaded with version 1.9.2.1 the tables are back :) so it means te data itself is not lost :)

This one should be easy to fix,



> and a secound one.. i dont know if the secound one is a related one because the plugin was disabling on unloading. so may just for information...
> 
> ```
> [13:45:12 INFO]: [Roulette] Disabling Roulette v1.9.3.1
> >....
> [13:45:12 ERROR]: [Minecraft] Error occurred while disabling Roulette v1.9.3.1 (Is it up to date?)
> java.lang.NoClassDefFoundError: Could not initialize class me.matsubara.roulette.npc.modifier.VisibilityModifier
> 	at me.matsubara.roulette.npc.NPC.visibility(NPC.java:283) ~[Roulette_1.9.3.1.jar:?]
> 	at me.matsubara.roulette.game.Game.remove(Game.java:902) ~[Roulette_1.9.3.1.jar:?]
> 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
> 	at me.matsubara.roulette.RoulettePlugin.onDisable(RoulettePlugin.java:182) ~[Roulette_1.9.3.1.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> >....at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:575) ~[PlugManX_2.3.1.jar:?]
> 	at com.rylinaux.plugman.command.UnloadCommand.execute(UnloadCommand.java:112) ~[PlugManX_2.3.1.jar:?]
> 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:98) ~[PlugManX_2.3.1.jar:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
> 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-307]
> 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
> 	at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
> 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
> ```

Are you using Plugman to enable/disable the plugin?

**Comment by CloudeLecaw** [comment]
yes and it works omplety fine to do this in 1.19.2  with the verion down to 1.9.2.1
..
so does it mmean u broke the abillity to load / unload it with plugin i1.9.3?

**Comment by CloudeLecaw** [comment]
di you may forgot the citicenz?....
well with 1.19.2 the last Citicens that can be used is  Citizens_2.0.30-Build2793
after that you need 1.19.3

The Tables now appear but the dealers are missing
Therefore i get an error in console with 1.9.3.2

```
[00:05:28] [Craft Scheduler Thread - 1787 - Roulette/WARN]: [Roulette] Plugin Roulette v1.9.3.2 generated an exception while executing task 134282356
java.lang.NoSuchMethodError: 'void com.comphenix.protocol.wrappers.PlayerInfoData.<init>(java.util.UUID, int, boolean, com.comphenix.protocol.wrappers.EnumWrappers$NativeGameMode, com.comphenix.protocol.wrappers.WrappedGameProfile, com.comphenix.protocol.wrappers.WrappedChatComponent, com.comphenix.protocol.wrappers.WrappedProfilePublicKey$WrappedProfileKeyData)'
	at me.matsubara.roulette.npc.modifier.VisibilityModifier.lambda$queuePlayerListChange$1(VisibilityModifier.java:93) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.lambda$send$1(NPCModifier.java:91) ~[Roulette_1.9.3.2.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.send(NPCModifier.java:87) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.send(NPCModifier.java:103) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.NPC.show(NPC.java:123) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:05:29] [Craft Scheduler Thread - 1773 - Roulette/WARN]: [Roulette] Plugin Roulette v1.9.3.2 generated an exception while executing task 134282356
java.lang.NoSuchMethodError: 'void com.comphenix.protocol.wrappers.PlayerInfoData.<init>(java.util.UUID, int, boolean, com.comphenix.protocol.wrappers.EnumWrappers$NativeGameMode, com.comphenix.protocol.wrappers.WrappedGameProfile, com.comphenix.protocol.wrappers.WrappedChatComponent, com.comphenix.protocol.wrappers.WrappedProfilePublicKey$WrappedProfileKeyData)'
	at me.matsubara.roulette.npc.modifier.VisibilityModifier.lambda$queuePlayerListChange$1(VisibilityModifier.java:93) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.lambda$send$1(NPCModifier.java:91) ~[Roulette_1.9.3.2.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.send(NPCModifier.java:87) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.modifier.NPCModifier.send(NPCModifier.java:103) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.NPC.show(NPC.java:123) ~[Roulette_1.9.3.2.jar:?]
	at me.matsubara.roulette.npc.NPCPool.lambda$npcTick$0(NPCPool.java:196) ~[Roulette_1.9.3.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by aematsubara** [comment]
I swear this time should be working

**Comment by CloudeLecaw** [comment]
it worked :D
