### ISSUE TITLE
Would be nice to have 1.19.4 support <3

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#28]
```
[03:03:01] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.asType(java.lang.invoke.MethodType)" because "mh" is null
[03:03:01] [Server thread/WARN]: 	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:542)
[03:03:01] [Server thread/WARN]: 	at Roulette_1.9.3.4.jar//me.matsubara.roulette.model.stand.PacketStand.createMetadataPacket(PacketStand.java:778)
[03:03:01] [Server thread/WARN]: 	at Roulette_1.9.3.4.jar//me.matsubara.roulette.model.stand.PacketStand.updateMetadata(PacketStand.java:773)
[03:03:01] [Server thread/WARN]: 	at Roulette_1.9.3.4.jar//me.matsubara.roulette.hologram.Hologram.update(Hologram.java:149)
[03:03:01] [Server thread/WARN]: 	at Roulette_1.9.3.4.jar//me.matsubara.roulette.hologram.Hologram$1.run(Hologram.java:237)
[03:03:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[03:03:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[03:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1482)
[03:03:01] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[03:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1396)
[03:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[03:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[03:03:01] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:03:01] [Server thread/WARN]: [Roulette] Task #41510 for Roulette v1.9.3.4 generated an exception
java.lang.NullPointerException: null
```

**Comment by aematsubara** [comment]
Done! Let me know of any errors

**Comment by CloudeLecaw** [comment]
looks liek its fixed <3 I played some round now without an issue =) So i will close the thread and reopen in only if may some issue appear
