### ISSUE TITLE
Please Update to 1.18.2 support

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#3]
Currently we dont see the chips. instead we see just steave heads.
You can also an error once each rount you start to play

```
[01:01:27 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[01:01:27 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[01:01:27 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[01:01:27 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[01:01:27 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[01:01:27 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[01:01:27 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[01:01:27 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.util.InventoryUpdate.updateInventory(InventoryUpdate.java:136)
[01:01:27 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.updateInventory(ChipGUI.java:131)
[01:01:27 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[01:01:27 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:01:27 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:01:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:01:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:01:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:43 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[01:01:43 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[01:01:43 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[01:01:43 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[01:01:43 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[01:01:43 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[01:01:43 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[01:01:43 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.util.InventoryUpdate.updateInventory(InventoryUpdate.java:136)
[01:01:43 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.updateInventory(ChipGUI.java:131)
[01:01:43 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.nextPage(ChipGUI.java:159)
[01:01:43 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.handleChipGUI(InventoryClick.java:156)
[01:01:43 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.onInventoryClick(InventoryClick.java:71)
[01:01:43 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor547.execute(Unknown Source)
[01:01:43 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[01:01:43 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:01:43 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:01:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[01:01:43 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2851)
[01:01:43 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[01:01:43 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
[01:01:43 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[01:01:43 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:01:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:01:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[01:01:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[01:01:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[01:01:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:01:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:44 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[01:01:44 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[01:01:44 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[01:01:44 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[01:01:44 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[01:01:44 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[01:01:44 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[01:01:44 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.util.InventoryUpdate.updateInventory(InventoryUpdate.java:136)
[01:01:44 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.updateInventory(ChipGUI.java:131)
[01:01:44 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.previousPage(ChipGUI.java:146)
[01:01:44 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.handleChipGUI(InventoryClick.java:153)
[01:01:44 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.onInventoryClick(InventoryClick.java:71)
[01:01:44 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor547.execute(Unknown Source)
[01:01:44 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[01:01:44 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:01:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:01:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[01:01:44 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2851)
[01:01:44 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[01:01:44 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
[01:01:44 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[01:01:44 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:01:44 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:01:44 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[01:01:44 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[01:01:44 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1506)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[01:01:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:01:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:01:52 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[01:01:52 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[01:01:52 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[01:01:52 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[01:01:52 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[01:01:52 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[01:01:52 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[01:01:52 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.util.InventoryUpdate.updateInventory(InventoryUpdate.java:136)
[01:01:52 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.updateInventory(ChipGUI.java:131)
[01:01:52 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.nextPage(ChipGUI.java:159)
[01:01:52 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.handleChipGUI(InventoryClick.java:156)
[01:01:52 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.listener.InventoryClick.onInventoryClick(InventoryClick.java:71)
[01:01:52 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor547.execute(Unknown Source)
[01:01:52 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[01:01:52 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:01:52 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:01:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[01:01:52 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2851)
[01:01:52 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[01:01:52 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
[01:01:52 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[01:01:52 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:01:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:01:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[01:01:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[01:01:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[01:01:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:01:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:02:42 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[01:02:42 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[01:02:42 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[01:02:42 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[01:02:42 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[01:02:42 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[01:02:42 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[01:02:42 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.util.InventoryUpdate.updateInventory(InventoryUpdate.java:136)
[01:02:42 WARN]:        at Roulette_1.8.jar//me.matsubara.roulette.gui.ChipGUI.updateInventory(ChipGUI.java:131)
[01:02:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[01:02:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[01:02:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:02:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:02:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:02:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

When i try to change the Skin of an Cupier ist asks for an URL to type in..
cant we use the old way where we gave them skins of other players or Citicenze anymore? :3

Server: Paper 1.18.2

**Comment by aematsubara** [comment]
Updated.

**Comment by CloudeLecaw** [comment]
U need to use Version 1.9 for 1.18.2

**Comment by aematsubara** [comment]
> U need to use Version 1.9 for 1.18.2

Yes. I've already updated in spigot, so should be working now
