### ISSUE TITLE
paper 1.20.2 error

### ISSUE THREAD

**Issue by rogerxavier93** [aematsubara/Roulette#32]
[12:32:42 ERROR]: Error occurred while enabling Roulette v1.9.6 (Is it up to date?)
java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
        at me.matsubara.roulette.util.xseries.SkullUtils.profileFromBase64(SkullUtils.java:198) ~[Roulette.jar:?]
        at me.matsubara.roulette.util.xseries.SkullUtils.setSkullBase64(SkullUtils.java:185) ~[Roulette.jar:?]
        at me.matsubara.roulette.util.xseries.SkullUtils.applySkin(SkullUtils.java:175) ~[Roulette.jar:?]
        at me.matsubara.roulette.model.Model.loadEquipment(Model.java:268) ~[Roulette.jar:?]
        at me.matsubara.roulette.model.Model.loadModel(Model.java:246) ~[Roulette.jar:?]
        at me.matsubara.roulette.model.Model.<init>(Model.java:107) ~[Roulette.jar:?]
        at me.matsubara.roulette.manager.GameManager.add(GameManager.java:83) ~[Roulette.jar:?]
        at me.matsubara.roulette.manager.GameManager.update(GameManager.java:203) ~[Roulette.jar:?]
        at me.matsubara.roulette.manager.GameManager.load(GameManager.java:48) ~[Roulette.jar:?]
        at me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:37) ~[Roulette.jar:?]
        at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:139) ~[Roulette.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-201]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-201]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-201]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:32:42 INFO]: [Roulette] Disabling Roulette v1.9.6

**Comment by aematsubara** [comment]
I'm waiting for some dependencies to update first!

**Comment by aematsubara** [comment]
Updated!
