### ISSUE TITLE
pls add 1.20.6 support

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#35]
Currently the plugin refuses to load on 1.20.6 papers servers

```
[23:56:40] [Server thread/INFO]: [Roulette] Enabling Roulette v2.0.3
[23:56:40] [Server thread/ERROR]: Error occurred while enabling Roulette v2.0.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at Roulette_2.0.3.jar/me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:79) ~[Roulette_2.0.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Failed to parse server version. Could not find any package starting with name: 'org.bukkit.craftbukkit.v'
	at Roulette_2.0.3.jar/me.matsubara.roulette.util.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:95) ~[Roulette_2.0.3.jar:?]
	... 13 more
[23:56:40] [Server thread/INFO]: [Roulette] Disabling Roulette v2.0.3
```

**Comment by CloudeLecaw** [comment]
Test with latest paper 1.20.6 it still does not load

```

**Comment by aematsubara** [comment]
Done!
