### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by Greazi-Times** [aematsubara/Roulette#4]
When startin Roulette it gives me this error I have been trying to search the values but I can't find it anywhere

```[18:01:59] [Server thread/ERROR]: Error occurred while enabling Roulette v1.8-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Action distance cannot be higher than spawn distance!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at me.matsubara.roulette.util.npc.NPCPool.<init>(NPCPool.java:86) ~[Roulette-1.8-SNAPSHOT.jar:?]
	at me.matsubara.roulette.util.npc.NPCPool$Builder.build(NPCPool.java:450) ~[Roulette-1.8-SNAPSHOT.jar:?]
	at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:115) ~[Roulette-1.8-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1604]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by aematsubara** [comment]
Seems to be a NPC issue, try increasing a bit your render-distance in the config.yml of the plugin, I'll check it out in-depth as soon as I can!

**Comment by Greazi-Times** [comment]
Oke so will try that for now.
I have it set to a very low tender distance as it is located some what covered and the moment you walk in to the room it loads.

Instaid of loading it behind a wall where no one sees it.
