### ISSUE TITLE
Money load error

### ISSUE THREAD

**Issue by vinziiz** [aematsubara/Roulette#40]
Every time this plugin load on my server after reboot. I use **Roulette v2.2** with **TheNewEconomy** for economy, i have tested **Essentials** but same error there... Server version are **CraftBukkit version 4314-Spigot-a759b62-bbb30e7 (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)** and of curse i use **PacketEvents API 2.4.0**. 

_Error code here under!_

```
[19:27:34] [Server thread/INFO]: [Roulette] Using TheNewEconomy v0.1.3.0 as the economy provider.
[19:27:34] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
[19:27:34] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
[19:27:34] [Server thread/WARN]:        at me.matsubara.roulette.util.Reflection.getMethod(Reflection.java:76)
[19:27:34] [Server thread/WARN]:        at me.matsubara.roulette.util.PluginUtils.<clinit>(PluginUtils.java:74)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
[19:27:34] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
[19:27:34] [Server thread/WARN]:        at me.matsubara.roulette.command.MainCommand.<clinit>(MainCommand.java:43)
[19:27:34] [Server thread/WARN]:        at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:137)
[19:27:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[19:27:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[19:27:34] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[19:27:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575)
[19:27:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489)
[19:27:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[19:27:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[19:27:34] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269)
[19:27:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[19:27:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[19:27:34] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by CloudeLecaw** [comment]
i agree sometimes ee have this too

```
[21:50:12] [Server thread/INFO]: [Roulette] Using CMIEInjector v1.0.2.4 as the economy provider.
[21:50:13] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)
[21:50:13] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[21:50:13] [Server thread/WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95)
[21:50:13] [Server thread/WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source)
[21:50:13] [Server thread/WARN]: 	at Roulette_2.2.jar//me.matsubara.roulette.util.Reflection.getMethod(Reflection.java:76)
[21:50:13] [Server thread/WARN]: 	at Roulette_2.2.jar//me.matsubara.roulette.util.PluginUtils.<clinit>(PluginUtils.java:74)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[21:50:13] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[21:50:13] [Server thread/WARN]: 	at Roulette_2.2.jar//me.matsubara.roulette.command.MainCommand.<clinit>(MainCommand.java:43)
[21:50:13] [Server thread/WARN]: 	at Roulette_2.2.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:137)
[21:50:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[21:50:13] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:50:13] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:50:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[21:50:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[21:50:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[21:50:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[21:50:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[21:50:13] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[21:50:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[21:50:13] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:50:13] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by CloudeLecaw** [comment]
We found out its the new paper that creates this error with nearly all economy hooking plugins.

We switched back to 1.21.1 Build 77 for now

**Comment by aematsubara** [comment]
Yes, this is an issue with the latest versions of paper, I fix is on the way along with the new big update

**Comment by CloudeLecaw** [comment]
your not the only that is effected many many plugins broke that work with head items..

**Comment by aematsubara** [comment]
Fixed on the latest release

**Comment by CloudeLecaw** [comment]
> Fixed on the latest release

u mean latest build of spigot?

**Comment by aematsubara** [comment]
> > Fixed on the latest release
> 
> u mean latest build of paper?

Latest release of Roulette

**Comment by CloudeLecaw** [comment]
> > > Fixed on the latest release
> > 
> > 
> > u mean latest build of paper?
> 
> Latest release of Roulette

yes i also saw that Roulette is ready for the new paper versions builds :)
