### ISSUE TITLE
first issue with 1.21.4

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#43]
I know the 1.21.4 is new. so let me show you some found issues on loading.

```
[02:57:06] [Server thread/INFO]: [Roulette] Using {CMIEInjector v1.0.2.4} as the economy provider.
[02:57:06] [Server thread/INFO]: [Roulette] All chips have been loaded from chips.yml!
[02:57:06] [Server thread/WARN]: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(ArmorStand)long to ()Object
[02:57:06] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:903)
[02:57:06] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:870)
[02:57:06] [Server thread/WARN]: 	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:541)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.util.Reflection.getFieldValue(Reflection.java:25)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.stand.PacketStand.<clinit>(PacketStand.java:275)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.stand.data.Pose.<clinit>(Pose.java:12)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.stand.StandSettings.<init>(StandSettings.java:63)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.Model.loadModel(Model.java:221)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.Model.handleModel(Model.java:123)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.model.Model.<init>(Model.java:116)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:159)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:304)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:125)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.manager.GameManager.init(GameManager.java:64)
[02:57:06] [Server thread/WARN]: 	at Roulette_3.1.2.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:220)
[02:57:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[02:57:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[02:57:06] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[02:57:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[02:57:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[02:57:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[02:57:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:769)
[02:57:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:531)
[02:57:06] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326)
[02:57:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236)
[02:57:06] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341)
[02:57:06] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:57:07] [Server thread/INFO]: [Roulette] All games have been loaded from games.yml!
```

after the server got started i got aggain and aggain this line:

```
[02:57:23] [Craft Scheduler Thread - 22 - Roulette/WARN]: [Roulette] Plugin Roulette v3.1.2 generated an exception while executing task 3261
java.lang.RuntimeException: Failed to create a packet!
	at Roulette_3.1.2.jar/me.matsubara.roulette.model.stand.PacketStand.createMetadata(PacketStand.java:591) ~[Roulette_3.1.2.jar:?]
	at Roulette_3.1.2.jar/me.matsubara.roulette.model.stand.PacketStand.spawn(PacketStand.java:398) ~[Roulette_3.1.2.jar:?]
	at Roulette_3.1.2.jar/me.matsubara.roulette.hologram.Hologram.update(Hologram.java:154) ~[Roulette_3.1.2.jar:?]
	at Roulette_3.1.2.jar/me.matsubara.roulette.hologram.Hologram$1.run(Hologram.java:252) ~[Roulette_3.1.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.4.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.Byte cannot be cast to class net.minecraft.core.Rotations (java.lang.Byte is in module java.base of loader 'bootstrap'; net.minecraft.core.Rotations is in unnamed module of loader java.net.URLClassLoader @7591083d)
	at net.minecraft.core.Rotations$1.encode(Rotations.java:10) ~[paper-1.21.4.jar:1.21.4-15-bb76819]
	at Roulette_3.1.2.jar/me.matsubara.roulette.model.stand.PacketStand.createMetadata(PacketStand.java:582) ~[Roulette_3.1.2.jar:?]
	... 9 more
```

So it would be nice to have an update for 1.21.4 :-)

**Comment by aematsubara** [comment]
Updated!
