### ISSUE TITLE
First seen issue on loading in Spigot 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#6]
```
[18:53:11] [Server thread/INFO]: [32m[me.matsubara.roulette.RoulettePlugin] [Roulette] Enabling Roulette v1.9-SNAPSHOT[0m
[18:53:11] [Server thread/INFO]: [32m[me.matsubara.roulette.RoulettePlugin] [Roulette] Using CMIEInjector as the economy provider.[0m
[18:53:11] [Server thread/INFO]: [32m[me.clip.placeholderapi.PlaceholderAPIPlugin] [PlaceholderAPI] Successfully registered expansion: roulette [1.9-SNAPSHOT][0m
[18:53:11] [Server thread/INFO]: [32m[me.matsubara.roulette.RoulettePlugin] [Roulette] All chips have been loaded from chips.yml![0m
[18:53:11] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityLiving
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.util.xseries.ReflectionUtils.getNMSClass(ReflectionUtils.java:200)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.util.xseries.ReflectionUtils.getNMSClass(ReflectionUtils.java:186)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.stand.PacketStand.<clinit>(PacketStand.java:145)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.addNew(Model.java:187)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.loadModel(Model.java:249)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.<init>(Model.java:103)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:119)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:11] [Server thread/WARN]: java.lang.NoSuchMethodException: no such method: net.minecraft.world.entity.decoration.EntityArmorStand.getDataWatcher()DataWatcher/invokeVirtual
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.stand.PacketStand.getMethod(PacketStand.java:896)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.stand.PacketStand.getMethod(PacketStand.java:886)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.stand.PacketStand.<clinit>(PacketStand.java:168)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.addNew(Model.java:187)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.loadModel(Model.java:249)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.model.Model.<init>(Model.java:103)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
[18:53:11] [Server thread/WARN]: 	at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:119)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513)
[18:53:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966)
[18:53:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:53:11] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: 'net.minecraft.network.syncher.DataWatcher net.minecraft.world.entity.decoration.EntityArmorStand.getDataWatcher()'
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
[18:53:11] [Server thread/WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
[18:53:11] [Server thread/WARN]: 	... 24 more
[18:53:11] [Server thread/ERROR]: [31m[Minecraft] Error occurred while enabling Roulette v1.9-SNAPSHOT (Is it up to date?)[0m
java.lang.ExceptionInInitializerError: null
	at me.matsubara.roulette.model.Model.addNew(Model.java:187) ~[?:?]
	at me.matsubara.roulette.model.Model.loadModel(Model.java:249) ~[?:?]
	at me.matsubara.roulette.model.Model.<init>(Model.java:103) ~[?:?]
	at me.matsubara.roulette.manager.GameManager.add(GameManager.java:81) ~[?:?]
	at me.matsubara.roulette.manager.GameManager.update(GameManager.java:201) ~[?:?]
	at me.matsubara.roulette.manager.GameManager.load(GameManager.java:46) ~[?:?]
	at me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35) ~[?:?]
	at me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "refc" is null
	at me.matsubara.roulette.model.stand.PacketStand.getConstructor(PacketStand.java:876) ~[?:?]
	at me.matsubara.roulette.model.stand.PacketStand.<clinit>(PacketStand.java:217) ~[?:?]
	... 19 more
```

**Comment by aematsubara** [comment]
While I think I have a solution for this, I'll have to wait for some dependencies (ProtocolLib & XSeries) to update to 1.19 before updating

**Comment by CloudeLecaw** [comment]
Xseries?

**Comment by aematsubara** [comment]
> Xseries?
Yup, a library that help me to provide support for older versions (1.12), in a few days should be updated,

> About protocollib
That's good! Thanks

**Comment by CloudeLecaw** [comment]
Might any news or chance for an 1.19 update yet? or are you wating for the 1.19.1? ;)
