### ISSUE TITLE
loading issue on 1.19?

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#8]
When i try to load roulette i get this error in console.... does it mean something went wrong?

```
>....[20:47:00 WARN]: [Roulette] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
>....

[20:47:00 INFO]: [Roulette] Using CMIEInjector as the economy provider.
>....
[20:47:00 WARN]: [Roulette] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.11.2-DEV-152 which is not a depend or softdepend of this plugin.
>....[20:47:00 INFO]: [PlaceholderAPI] Successfully registered expansion: roulette [1.9.1-SNAPSHOT]
>....

[20:47:00 INFO]: [Roulette] All chips have been loaded from chips.yml!
>....
[20:47:06 WARN]: java.net.SocketTimeoutException: Read timed out
>....[20:47:06 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
>....

[20:47:06 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
>....
[20:47:06 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
>....
[20:47:06 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
>....
[20:47:06 WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
>....
[20:47:06 WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
>....
[20:47:06 WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
>....
[20:47:06 WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
>....
[20:47:06 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1455)
>....
[20:47:06 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059)
>....
[20:47:06 WARN]: 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
>....
[20:47:06 WARN]: 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
>....
[20:47:06 WARN]: 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
>....
[20:47:06 WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791)
>....
[20:47:06 WARN]: 	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
>....
[20:47:06 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
>....
[20:47:06 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
>....
[20:47:06 WARN]: 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
>....
[20:47:06 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.util.npc.profile.Profile.makeRequest(Profile.java:205)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.util.npc.profile.Profile.complete(Profile.java:171)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.util.npc.profile.Profile.complete(Profile.java:140)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.game.Game.setNPC(Game.java:212)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.game.Game.<init>(Game.java:140)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.manager.GameManager.add(GameManager.java:81)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.manager.GameManager.update(GameManager.java:201)
>....[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.manager.GameManager.load(GameManager.java:46)
>....

[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.manager.GameManager.<init>(GameManager.java:35)
>....
[20:47:06 WARN]: 	at Roulette_1.9.1.jar//me.matsubara.roulette.RoulettePlugin.onEnable(RoulettePlugin.java:119)
>....
[20:47:06 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>....
[20:47:06 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>....
[20:47:06 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
>....
[20:47:06 WARN]: 	at PlugManX_2.3.0.jar//com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309)
>....
[20:47:06 WARN]: 	at PlugManX_2.3.0.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120)
>....
[20:47:06 WARN]: 	at PlugManX_2.3.0.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
>....
[20:47:06 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>....
[20:47:06 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
>....
[20:47:06 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
>....
[20:47:06 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:870)
>....
[20:47:06 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
>....
[20:47:06 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
>....
[20:47:06 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
>....
[20:47:06 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
>....
[20:47:06 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
>....
[20:47:06 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by CloudeLecaw** [comment]
solved with restart
